algoritmo "Exercício 07 - Conversão Cotação Dólar para Real"
// Autor: Katharine Fernandes
// Data: 08/28/2023

// Seção de Declarações 
var
cotDolar,qntDolar,valReal:real

// Seção de Comandos
inicio

// ENTRADAS
escreva("Digite o valor da cotação do dólar: ")
leia(cotDolar)
escreva("Digite a quantidade de dólares: ")
leia(qntDolar)

// PROCESSAMENTO
valReal <- qntDolar * cotDolar

// SAÍDA
escreval("O valor dos dólares em reais eh:", valReal)

fimalgoritmo
