algoritmo "Exercício 04 - Conversão de Celsius para Fahrenheit"
// Autor: Katharine Fernandes
// Data: 08/28/2023

// Seção de Declarações 
var
celsius,fahrenheit:real

// Seção de Comandos
inicio

// ENTRADA
escreva("Digite o valor da temperatura em Celsisus: ")
leia(celsius)

// PROCESSAMENTO
fahrenheit <- (9 * celsius + 160) / 5

// SAÍDA
escreval("A temperatura convertida em Fahrenheit eh:", fahrenheit)

fimalgoritmo
