algoritmo "Exemplo 03 - Aula 03"
// Autor: Katharine Fernandes
// Data : 04/09/2023

// Seção de Declarações
var

num:inteiro

// Seção de Comandos
inicio

// ENTRADAS
escreva("Insira um número inteiro:")
leia(num)

// ESTRUTURA DE CONDIÇÃO COMPOSTA

se ((num mod 3) = 0) entao
   escreval("Número multiplo de 3")
senao
   escreval("Número não é multiplo de 3")
fimse


fimalgoritmo
