algoritmo "Exemplo 01 - Aula 03"
// Autor: Katharine Fernandes
// Data : 04/09/2023

// Seção de Declarações
var

num1,num2,soma:real

// Seção de Comandos
inicio

// ENTRADAS
escreva("Insira o primeiro valor:")
leia(num1)
escreva("Insira o segundo valor:")
leia(num2)

// PROCESSAMENTO
soma <- num1 + num2

// ESTRUTURA DE SELEÇÃO SIMPLES
se (soma > 10) entao
   escreval("Soma:", soma)
fimse

fimalgoritmo
