algoritmo "Exercício 1 - Lista Extra 1"
// Autor: Katharine Fernandes
// Data : 04/09/2023

// Seção de Declarações
var
custoEspec, precoConv:real
qntConv:inteiro

// Seção de Comandos
inicio

// ENTRADAS
escreva("Informe o custo do espetáculo:")
leia(custoEspec)
escreva("Informe o preço do convite")
leia(precoConv)

// PROCESSAMETO
qntConv <- custoEspec/precoConv

// SAÍDAS
escreval("A quatidade de covites deve ser igual a:", qnt

fimalgoritmo
